require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'vendor/**/*'
    - 'Rakefile'
    - 'scripts/**/*'
    - 'bin/*'
    - 'example/**/*'
    - 'gemfiles/*'
    - 'Appraisals'
    - 'tmp/**/*'

Style/GuardClause:
  Enabled: no

Style/Documentation:
  Enabled: no

Style/HashSyntax:
  Enabled: no

Style/IfUnlessModifier:
  Enabled: no

RSpec/NestedGroups:
  Max: 4

RSpec/ExampleLength:
  Enabled: no

RSpec/MultipleExpectations:
  Enabled: no

RSpec/EmptyExampleGroup:
  Enabled: no

RSpec/DescribeClass:
  Enabled: no

Metrics/BlockLength:
  Enabled: no

Metrics/MethodLength:
  Enabled: no

Metrics/AbcSize:
  Enabled: no

Metrics/ClassLength:
  Enabled: no

Metrics/ParameterLists:
  Enabled: no

Lint/UnusedMethodArgument:
  Enabled: no

Style/FrozenStringLiteralComment:
  Enabled: no

Metrics/LineLength:
  Max: 120
