version: 2
jobs:
  rubycritic:
    docker:
      - image: circleci/ruby:2.4
        environment:
          LOG_LEVEL: DEBUG
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "eh-mailer.gemspec" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "eh-mailer.gemspec" }}
      - run: bundle exec rubycritic -s 90 --no-browser -f console --suppress-ratings lib/

  rubocop:
    docker:
      - image: circleci/ruby:2.4
        environment:
          LOG_LEVEL: DEBUG
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "eh-mailer.gemspec" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "eh-mailer.gemspec" }}
      - run: bundle exec rubocop

  unit:
    docker:
      - image: circleci/ruby:2.4
        environment:
          LOG_LEVEL: DEBUG
    working_directory: ~/app
    steps:
      - checkout

      # download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "eh-mailer.gemspec" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
            bundle exec appraisal install

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "eh-mailer.gemspec" }}

      # run tests!
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/units/**/*_spec.rb" | \
              circleci tests split --split-by=timings)"

            COVERAGE=true bundle exec appraisal rspec \
              --format progress \
              --color \
              $TEST_FILES

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

  integration:
    docker:
      - image: circleci/ruby:2.4
        environment:
          LOG_LEVEL: DEBUG
          INTEGRATION_TEST: true
          RAILS_START_TIMEOUT: 50
      - image: wurstmeister/zookeeper
      - image: wurstmeister/kafka:0.11.0.1
        environment:
          KAFKA_ADVERTISED_HOST_NAME: localhost
          KAFKA_ADVERTISED_PORT: 9092
          KAFKA_PORT: 9092
          KAFKA_ZOOKEEPER_CONNECT: localhost:2181
          KAFKA_DELETE_TOPIC_ENABLE: true

    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
            bundle exec appraisal install
      - run: dockerize -wait tcp://localhost:9092 -timeout 1m
      - run:
          name: run integration tests
          command: |
            bundle exec appraisal bundle exec rspec spec/integrations/*_spec.rb

  publish_github_release:
    working_directory: ~/app
    docker:
      - image: ehdevops/release_lib:0.0.1
        environment:
          GITHUB_REPOSITORY: 'Thinkei/eh-mailer'
    steps:
      - checkout
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(echo `cat ~/app/app.json` | jq .version | tr -d \")
            RELEASE_NOTE=$(node /usr/src/app/release_note.js -f ~/app/CHANGELOG.md -v $VERSION)
            echo "${RELEASE_NOTE}" > /release/release_note.txt
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -n ${VERSION} -b "${RELEASE_NOTE}" -delete ${VERSION} /release/

  publish:
    docker:
      - image: ehdevops/ruby240:latest
    steps:
      - checkout
      - run: bundle check || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - run:
          name: Deploy to gemfury
          command: |
            bundle exec ruby scripts/publish.rb

  publish_development:
    docker:
      - image: ehdevops/ruby240:latest
    steps:
      - checkout
      - run: bundle check || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - run:
          name: Deploy to gemfury
          command: |
            bundle exec ruby scripts/publish_development.rb

workflows:
  version: 2
  test:
    jobs:
      - unit:
          context: org-global
      - integration:
          context: org-global
      - rubycritic:
          context: org-global
      - rubocop:
          context: org-global
      - publish_new_version:
          type: approval
          filters:
            branches:
              only:
                - master
      - publish_development:
          context: org-global
          filters:
            branches:
              only:
                - development
          requires:
            - unit
            - rubocop
      - publish_github_release:
          context: org-global
          filters:
            branches:
              only:
                - master
          requires:
            - unit
            - integration
            - rubocop
            - rubycritic
            - publish_new_version
      - publish:
          context: org-global
          filters:
            branches:
              only:
                - master
          requires:
            - rubocop
            - unit
            - integration
            - rubycritic
            - publish_new_version
            - publish_github_release

