version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  rubycritic:
    docker:
      - image: circleci/ruby:2.3
        environment:
          LOG_LEVEL: DEBUG
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "eh-mailer.gemspec" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "eh-mailer.gemspec" }}
      - run: bundle exec rubycritic -s 90 --no-browser -f console --suppress-ratings lib/

  rubocop:
    docker:
      - image: circleci/ruby:2.3
        environment:
          LOG_LEVEL: DEBUG
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "eh-mailer.gemspec" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "eh-mailer.gemspec" }}
      - run: bundle exec rubocop

  unit:
    docker:
      - image: circleci/ruby:2.3
        environment:
          LOG_LEVEL: DEBUG
    working_directory: ~/app
    steps:
      - checkout

      # download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "eh-mailer.gemspec" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
            bundle exec appraisal install

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "eh-mailer.gemspec" }}

      # run tests!
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/units/**/*_spec.rb" | \
              circleci tests split --split-by=timings)"

            COVERAGE=true bundle exec appraisal rspec \
              --format progress \
              --color \
              $TEST_FILES
      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
      - codecov/upload:
          file: /tmp/test-results


  integration_rails_4:
    docker:
      - image: circleci/ruby:2.3
        environment:
          LOG_LEVEL: DEBUG
          INTEGRATION_TEST: true
      - image: wurstmeister/zookeeper
      - image: wurstmeister/kafka:0.11.0.1
        environment:
          KAFKA_ADVERTISED_HOST_NAME: localhost
          KAFKA_ADVERTISED_PORT: 9092
          KAFKA_PORT: 9092
          KAFKA_ZOOKEEPER_CONNECT: localhost:2181
          KAFKA_DELETE_TOPIC_ENABLE: true
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            BUNDLE_GEMFILE=./gemfiles/rails_4.gemfile bundle install --path ~/app/vendor/bundle
      - run:
          name: run integration tests
          command: |
            bundle exec rspec spec/integrations/rails_integration_spec.rb

  integration_rails_5:
    docker:
      - image: circleci/ruby:2.3
        environment:
          LOG_LEVEL: DEBUG
          INTEGRATION_TEST: true
      - image: wurstmeister/zookeeper
      - image: wurstmeister/kafka:0.11.0.1
        environment:
          KAFKA_ADVERTISED_HOST_NAME: localhost
          KAFKA_ADVERTISED_PORT: 9092
          KAFKA_PORT: 9092
          KAFKA_ZOOKEEPER_CONNECT: localhost:2181
          KAFKA_DELETE_TOPIC_ENABLE: true
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            BUNDLE_GEMFILE=./gemfiles/rails_5.gemfile bundle install --path ~/app/vendor/bundle
      - run:
          name: run integration tests
          command: |
             bundle exec rspec spec/integrations/rails_integration_spec.rb

workflows:
  version: 2
  test:
    jobs:
      - unit
      - integration_rails_4
      - integration_rails_5
      - rubycritic
      - rubocop
